version: '2.1'
services:
  sonar:
    build: ./sonarqube_server
    links:
      - sonar_postgres
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      - "SONARQUBE_JDBC_USERNAME=sonar"
      - "SONARQUBE_JDBC_PASSWORD=sonar"
      - "SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_postgres/sonar"
    restart: always
    volumes:
      - "sonarqube_data_drive:/opt/sonarqube/data"

  sonar_postgres:
    image: "postgres:9.6"
    restart: always
    environment:
      - "POSTGRES_PASSWORD=sonar"
      - "POSTGRES_USER=sonar"
    volumes:
      - "postgres_data_drive:/var/lib/postgresql/data"
volumes:
  postgres_data_drive:
  sonarqube_data_drive:
